stats dir is 11:00:43.04.26.2016.evince.stats.experiment.config.fq.64
<started streamserver on node-0.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-1.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-3.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-4.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-5.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-6.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-7.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-8.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-9.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-10.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-11.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-12.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-13.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-14.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-15.arquinn-QV15174.dift-pg0.apt.emulab.net>
<started streamserver on node-16.arquinn-QV15174.dift-pg0.apt.emulab.net>
['-stats', '-c', '-w', '-lowmem', '-s', '-v', 'tmp_results', 'seqtt.results', '-hs', '.arquinn-QV15174.dift-pg0.apt.emulab.net', '-seq']

remote_dir /local/src/omniplay/test/seqtt.results
local_dir /home/arquinn/Documents/omniplay/test/experiment_config_files/evince/seqtt.results
seqtt.reults must have already existed
Traceback (most recent call last):
  File "./streamlined_experiment.py", line 238, in <module>
    main()
  File "./streamlined_experiment.py", line 188, in main
    sync_files("arquinn",cmd_args.password,tconfs,sync_cmd_args)
  File "./streamlined_experiment.py", line 44, in sync_files
    last_test.start_ctrl(user, password, args)
  File "/home/arquinn/Documents/omniplay/test/orchestration/server.py", line 152, in start_ctrl
    self.ctrl_host.start_ctrl(user, password, flags)
  File "/home/arquinn/Documents/omniplay/test/orchestration/server.py", line 107, in start_ctrl
    result = shell.run(args,cwd=CLOUDLAB_STREAMCTL_DIR)
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 158, in run
    return self.spawn(*args, **kwargs).wait_for_result()
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 359, in wait_for_result
    self._result = self._generate_result()
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 371, in _generate_result
    stderr_output
  File "/usr/local/lib/python2.7/dist-packages/spur/results.py", line 9, in result
    raise result.to_error()
spur.results.RunProcessError: return code: 255
output: b''
stderr output: b'found that we need 1740 files\nwe have 1740 cache files to send to node-0\nwe have 1740 cache files to send to node-1\nwe have 1740 cache files to send to node-3\nwe have 1740 cache files to send to node-4\nwe have 1740 cache files to send to node-5\nwe have 1740 cache files to send to node-6\nwe have 1740 cache files to send to node-7\nCannot read sync results, rc=-1\nCommand exited with non-zero status 255\n0.03user 0.14system 15:57.12elapsed 0%CPU (0avgtext+0avgdata 4040maxresident)k\n0inputs+0outputs (0major+1977minor)pagefaults 0swaps\n'
